[CmdletBinding()]
param([string]$OutputDirectory = '_site')

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$siteRoot = Join-Path $repoRoot 'site'
$outputRoot = Join-Path $repoRoot $OutputDirectory

function Write-Utf8File {
    param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][AllowEmptyString()][string]$Content)
    $parent = Split-Path -Parent $Path
    if ($parent) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
    [IO.File]::WriteAllText($Path, $Content, [Text.UTF8Encoding]::new($false))
}
function Html([AllowEmptyString()][string]$Value) { [Net.WebUtility]::HtmlEncode($Value) }
function Inline-Markdown {
    param([string]$Text)
    $value = Html (($Text.Trim()) -replace '(?is)<a\b[^>]*>(.*?)</a>', '$1' -replace '(?is)</?pre\b[^>]*>', '' -replace '(?is)<br\s*/?>', ' ')
    $value = [regex]::Replace($value, '!\[([^\]]*)\]\(([^)]+)\)', { param($m) '<img src="' + $m.Groups[2].Value + '" alt="' + $m.Groups[1].Value + '" loading="lazy">' })
    $value = [regex]::Replace($value, '\[([^\]]+)\]\(([^)]+)\)', { param($m) $href = $m.Groups[2].Value.Trim() -replace '\s+&quot;[^&]*&quot;$', ''; if ($href -match '(?i)\.md(?:#.*)?$') { $href = $href -replace '(?i)\.md(?=#|$)', '.html' }; '<a href="' + $href + '">' + $m.Groups[1].Value + '</a>' })
    $value = [regex]::Replace($value, '`([^`]+)`', '<code>$1</code>')
    $value = [regex]::Replace($value, '\*\*([^*]+)\*\*', '<strong>$1</strong>')
    [regex]::Replace($value, '(?<!\*)\*([^*]+)\*(?!\*)', '<em>$1</em>')
}
function Flush-Paragraph { param([Collections.Generic.List[string]]$Lines, [Text.StringBuilder]$Builder); if ($Lines.Count -eq 0) { return }; [void]$Builder.AppendLine('<p>' + (Inline-Markdown ($Lines -join ' ')) + '</p>'); $Lines.Clear() }
function Flush-List { param([Collections.Generic.List[string]]$Items, [Text.StringBuilder]$Builder, [ref]$Type); if ($Items.Count -eq 0) { return }; $tag = if ($Type.Value -eq 'ol') { 'ol' } else { 'ul' }; [void]$Builder.AppendLine('<' + $tag + '>'); foreach ($item in $Items) { [void]$Builder.AppendLine('<li>' + (Inline-Markdown $item) + '</li>') }; [void]$Builder.AppendLine('</' + $tag + '>'); $Items.Clear(); $Type.Value = '' }
function Flush-Table { param([Collections.Generic.List[string]]$Rows, [Text.StringBuilder]$Builder); if ($Rows.Count -lt 2) { $Rows.Clear(); return }; $header = $Rows[0].Trim().Trim('|') -split '\s*\|\s*'; [void]$Builder.AppendLine('<table><thead><tr>'); foreach ($cell in $header) { [void]$Builder.AppendLine('<th>' + (Inline-Markdown $cell) + '</th>') }; [void]$Builder.AppendLine('</tr></thead><tbody>'); foreach ($row in ($Rows | Select-Object -Skip 2)) { [void]$Builder.AppendLine('<tr>'); foreach ($cell in ($row.Trim().Trim('|') -split '\s*\|\s*')) { [void]$Builder.AppendLine('<td>' + (Inline-Markdown $cell) + '</td>') }; [void]$Builder.AppendLine('</tr>') }; [void]$Builder.AppendLine('</tbody></table>'); $Rows.Clear() }
function Markdown-ToHtml {
    param([string]$Markdown, [switch]$SkipFirstH1)
    $builder=[Text.StringBuilder]::new(); $paragraph=[Collections.Generic.List[string]]::new(); $items=[Collections.Generic.List[string]]::new(); $rows=[Collections.Generic.List[string]]::new(); $type=''; $code=[Collections.Generic.List[string]]::new(); $inCode=$false; $language=''; $h1Skipped=$false
    foreach ($line in ($Markdown -split '\r?\n')) {
        if ($inCode) { if ($line -match '^\s*```') { $class=if($language){' class="language-' + ([regex]::Replace($language.ToLowerInvariant(),'[^a-z0-9-]','')) + '"'}else{''}; [void]$builder.Append('<pre><code' + $class + '>' + (Html ($code -join "`n")) + '</code></pre>'); $inCode=$false; $code.Clear(); $language='' } else { $code.Add($line) }; continue }
        if ($line -match '^\s*```\s*(.*)$') { Flush-Paragraph $paragraph $builder; Flush-List $items $builder ([ref]$type); Flush-Table $rows $builder; $inCode=$true; $language=$Matches[1].Trim(); continue }
        if ($line -match '^\s*$') { Flush-Paragraph $paragraph $builder; Flush-List $items $builder ([ref]$type); Flush-Table $rows $builder; continue }
        if ($SkipFirstH1 -and -not $h1Skipped -and $line -match '^\s*#\s+(.+?)\s*$') { Flush-Paragraph $paragraph $builder; $h1Skipped=$true; continue }
        if ($line -match '^\s*(#{1,6})\s+(.+?)\s*$') { Flush-Paragraph $paragraph $builder; Flush-List $items $builder ([ref]$type); Flush-Table $rows $builder; $level=$Matches[1].Length; [void]$builder.AppendLine('<h' + $level + '>' + (Inline-Markdown $Matches[2]) + '</h' + $level + '>'); continue }
        if ($line -match '^\s*>\s?(.*)$') { Flush-Paragraph $paragraph $builder; Flush-List $items $builder ([ref]$type); Flush-Table $rows $builder; [void]$builder.AppendLine('<blockquote>' + (Inline-Markdown $Matches[1]) + '</blockquote>'); continue }
        if ($line.Trim() -match '^(?:\|.*\|)$' -or ($line -split '\|').Count -ge 3) { Flush-Paragraph $paragraph $builder; Flush-List $items $builder ([ref]$type); $rows.Add($line); continue }
        if ($rows.Count -gt 0) { Flush-Table $rows $builder }
        if ($line -match '^\s*[-*+]\s+(.+)$') { Flush-Paragraph $paragraph $builder; if ($type -and $type -ne 'ul') { Flush-List $items $builder ([ref]$type) }; $type='ul'; $items.Add($Matches[1]); continue }
        if ($line -match '^\s*\d+[.)]\s+(.+)$') { Flush-Paragraph $paragraph $builder; if ($type -and $type -ne 'ol') { Flush-List $items $builder ([ref]$type) }; $type='ol'; $items.Add($Matches[1]); continue }
        if ($line.Trim() -match '^(---+|\*\*\*+)$') { Flush-Paragraph $paragraph $builder; Flush-List $items $builder ([ref]$type); [void]$builder.AppendLine('<hr>'); continue }
        Flush-List $items $builder ([ref]$type); $paragraph.Add($line.Trim())
    }
    if ($inCode) { [void]$builder.Append('<pre><code>' + (Html ($code -join "`n")) + '</code></pre>') }; Flush-Paragraph $paragraph $builder; Flush-List $items $builder ([ref]$type); Flush-Table $rows $builder; $builder.ToString()
}
function Title-For { param([string]$Markdown,[string]$Path); $match=[regex]::Match($Markdown,'(?m)^\s*#\s+(.+?)\s*$'); if($match.Success){return ($match.Groups[1].Value.Trim() -replace '[*_`]','')}; $name=[IO.Path]::GetFileNameWithoutExtension($Path); if($name -ieq 'README'){return 'Repository overview'}; [Globalization.CultureInfo]::InvariantCulture.TextInfo.ToTitleCase(($name -replace '[_-]+',' ').ToLowerInvariant()) }
function Summary-For { param([string]$Markdown,[string]$Title); $inCode=$false; foreach($line in ($Markdown -split '\r?\n')){$value=$line.Trim();if($value -match '^```'){$inCode=-not $inCode;continue};if($inCode -or -not $value -or $value -match '^#{1,6}\s' -or $value -match '^\s*[|>]' -or $value -match '^\s*[-*+]\s'){continue};$value=($value -replace '!\[([^]]+)\]\([^)]+\)','$1' -replace '\[([^]]+)\]\([^)]+\)','$1' -replace '`','').Trim();if($value.Length -ge 30){if($value.Length -gt 190){return $value.Substring(0,187).TrimEnd()+'…'};return $value}}; 'Reference documentation for ' + $Title + '.' }
function Category-For { param([string]$Path,[string]$Title);$value="$Path $Title".ToLowerInvariant();$leaf=[IO.Path]::GetFileName($Path).ToLowerInvariant();if(($Path -notmatch '^modules/') -and ($leaf -eq 'readme.md' -or $value -match 'architecture|modules_index')){return [pscustomobject]@{Key='guides';Title='Architecture & Design';Description='Understand OCI topology, shared controls, modules, and design boundaries.';Icon='◇'}};if($value -match 'reference|terraform|naming|standard|tagging|module|example'){return [pscustomobject]@{Key='reference';Title='Modules & Reference';Description='Reusable module guidance, standards, configuration details, and implementation reference.';Icon='⌁'}};if($value -match 'runbook|deployment|pipeline|validation|howto|how-to|authentication|provision'){return [pscustomobject]@{Key='runbooks';Title='Deployment Runbooks';Description='Procedures for deploying, validating, operating, and extending the OCI template.';Icon='▦'}};[pscustomobject]@{Key='guides';Title='Architecture & Design';Description='Understand OCI topology, shared controls, modules, and design boundaries.';Icon='◇'} }

& (Join-Path $PSScriptRoot 'Generate-DocsManifest.ps1')
$config=Get-Content (Join-Path $siteRoot 'site.json') -Raw | ConvertFrom-Json; $manifest=Get-Content (Join-Path $repoRoot 'docs-manifest.json') -Raw | ConvertFrom-Json; $sourcePaths=@($manifest.documents | Where-Object {$_ -match '(?i)\.md$'}); if(-not $sourcePaths.Count){throw 'No Markdown documents found in docs-manifest.json'}
if(Test-Path $outputRoot){Remove-Item $outputRoot -Recurse -Force}; New-Item $outputRoot -ItemType Directory -Force | Out-Null; $assetVersion=[DateTime]::UtcNow.Ticks.ToString(); $pages=@(foreach($sourcePath in $sourcePaths){$normalized=$sourcePath.Replace('\','/');$markdown=Get-Content (Join-Path $repoRoot ($normalized -replace '/','\')) -Raw;$title=Title-For $markdown $normalized;$category=Category-For $normalized $title;[pscustomobject]@{SourcePath=$normalized;OutputPath=([IO.Path]::ChangeExtension($normalized,'.html')).ToLowerInvariant();Title=$title;Summary=(Summary-For $markdown $title);Html=(Markdown-ToHtml $markdown -SkipFirstH1);CategoryKey=$category.Key;CategoryTitle=$category.Title;CategoryDescription=$category.Description;CategoryIcon=$category.Icon}})|Sort-Object Title
$template=Get-Content (Join-Path $siteRoot 'template.html') -Raw; $siteTitle=Html ([string]$config.title);$description=Html ([string]$config.description);$eyebrow=Html ([string]$config.eyebrow);$repoUrl=Html ([string]$config.repository)
function Prefix-For { param([string]$OutputPath);$dir=Split-Path -Parent ($OutputPath -replace '/','\');if(-not $dir){return ''};return (('../' * @($dir -split '[\\/]+'|Where-Object {$_}).Count) -join '') }
function Render-Page { param([string]$Content,[string]$PageTitle,[string]$OutputPath);$prefix=Prefix-For $OutputPath;$template.Replace('{{DESCRIPTION}}',$description).Replace('{{PAGE_TITLE}}',(Html $PageTitle)).Replace('{{SITE_TITLE}}',$siteTitle).Replace('{{GITHUB_URL}}',$repoUrl).Replace('{{ROOT_PREFIX}}',$prefix).Replace('{{ASSET_VERSION}}',$assetVersion).Replace('{{CONTENT}}',$Content) }
$categories=@([pscustomobject]@{Key='guides';Title='Architecture & Design';Description='Understand OCI topology, shared controls, modules, and design boundaries.';Icon='◇'},[pscustomobject]@{Key='runbooks';Title='Deployment Runbooks';Description='Procedures for deploying, validating, operating, and extending the OCI template.';Icon='▦'},[pscustomobject]@{Key='reference';Title='Modules & Reference';Description='Reusable module guidance, standards, configuration details, and implementation reference.';Icon='⌁'})
$categoryMarkup=($categories|ForEach-Object{$category=$_;$items=@($pages|Where-Object CategoryKey -eq $category.Key);$links=($items|ForEach-Object{'<a class="category-card-link" data-search-card href="'+$_.OutputPath+'"><span>'+ (Html $_.Title) +'</span><span aria-hidden="true">↗</span></a>'}) -join "`n";$label=if($items.Count -eq 1){'1 document →'}else{"$($items.Count) documents →"};'<article class="category-card" data-category="'+$category.Key+'"><span class="category-card-head"><span class="category-icon" aria-hidden="true">'+$category.Icon+'</span><strong>'+ (Html $category.Title) +'</strong></span><p>'+ (Html $category.Description) +'</p><span class="category-card-links">'+$links+'</span><span class="category-meta">'+$label+'</span></article>'}) -join "`n"
$heroLinks=($pages|Select-Object -First 2|ForEach-Object{'<a class="hero-link" href="'+$_.OutputPath+'">'+(Html $_.Title)+' ↗</a>'}) -join "`n      ";$count=if($pages.Count -eq 1){'1 document'}else{"$($pages.Count) documents"}
$index=@"
<main class="catalog-view"><section class="hero"><p class="eyebrow">$eyebrow</p><h1>$siteTitle</h1><p class="hero-copy">$description</p>$heroLinks</section><div class="catalog-toolbar"><form data-search-form role="search"><label class="sr-only" for="site-search">Search documentation</label><div class="search-wrap"><input class="search-input" id="site-search" type="search" placeholder="Search documentation" autocomplete="off"></div></form><div class="doc-count">$count</div></div><section class="category-overview"><div class="category-intro"><h2 class="catalog-heading">Explore the library</h2><p>Choose a collection to browse architecture guidance, deployment runbooks, or supporting reference material.</p></div><div class="category-grid">$categoryMarkup</div></section><p class="search-empty" data-search-empty hidden>No documents match your search.</p></main>
"@
Write-Utf8File (Join-Path $outputRoot 'index.html') (Render-Page $index 'Home' 'index.html')
foreach($page in $pages){$prefix=Prefix-For $page.OutputPath;$sourceHref="$repoUrl/blob/main/$($page.SourcePath)";$content='<main class="reader-view"><div class="reader-navigation"><a class="back-button" href="'+$prefix+'index.html">← All documents</a><span class="reader-path">'+(Html $page.SourcePath)+'</span></div><article class="reader"><div class="reader-tools"><span class="file-label">'+(Html $page.SourcePath)+'</span><a class="github-link" href="'+$sourceHref+'" target="_blank" rel="noopener">View source on GitHub ↗</a></div><div class="markdown-body">'+$page.Html+'</div></article></main>';Write-Utf8File (Join-Path $outputRoot ($page.OutputPath -replace '/','\')) (Render-Page $content $page.Title $page.OutputPath)}
$search=@($pages|ForEach-Object{[ordered]@{title=$_.Title;path=$_.OutputPath;summary=$_.Summary}})|ConvertTo-Json -Depth 4;Write-Utf8File (Join-Path $outputRoot 'search-index.json') ($search+"`n")
$assetPaths=@(git -C $repoRoot ls-files|Where-Object{$_ -match '(?i)\.(png|jpg|jpeg|gif|svg|pdf)$'});foreach($assetPath in $assetPaths){$source=Join-Path $repoRoot ($assetPath -replace '/','\');$destination=Join-Path $outputRoot ($assetPath -replace '/','\');New-Item (Split-Path $destination -Parent) -ItemType Directory -Force|Out-Null;Copy-Item $source $destination -Force}
Copy-Item (Join-Path $siteRoot 'styles.css') (Join-Path $outputRoot 'styles.css');Copy-Item (Join-Path $siteRoot 'site.js') (Join-Path $outputRoot 'site.js');Write-Utf8File (Join-Path $outputRoot '.nojekyll') '';Write-Host "Built OCI template documentation site with $($pages.Count) pages at $outputRoot"
